### ISSUE TITLE
How can I save a trained model? 

### ISSUE THREAD

**Issue by laizef** [jilljenn/ktm#4]
Hello, I found that the model was trained and used for prediction in a single function `FM.run()`, but how can I save or load a trained model? I would appreciate it if the problem could be addressed.

**Comment by laizef** [comment]
I got it... The model can not be saved when we choose the MCMC method.

**Comment by jilljenn** [comment]
Actually you can get the model weights!
See [on this Mangaki project](https://github.com/mangaki/zero/blob/master/zero/fma.py#L58).

**Comment by jilljenn** [comment]
I will add some functions to do the same on KTM. On maybe it would be better to do it directly on pywFM.

**Comment by jilljenn** [comment]
It is now done: https://github.com/jilljenn/ktm/blob/master/fm.py#L26
Please try and let me know.
