### ISSUE TITLE
KeyError: 'tutor'

### ISSUE THREAD

**Issue by Jinghaoma** [jilljenn/ktm#5]
Hello jilljenn

  I am learning this field. I try to reproduce your results, following the instructions in the readme to execute python encode.py --users --items, but the program reports an error and returns KeyError: 'tutor'. This seems to be due to the first in the encode.py file 73 lines

`X['tutor'] = onehotize(df['tutor'], len(df['tutor'].unique()))`

There is no tutor column in the sample data, so it shall be a bug right？May i have any suggestions?Thank you very much

best wishes

MA Jinghao

**Comment by jilljenn** [comment]
Hi! I fixed it but I forgot to push my changes. It should now work! Thanks for your comments.
