### ISSUE TITLE
Something about the visualizing embedding

### ISSUE THREAD

**Issue by 90cyh** [jilljenn/ktm#6]
Hello, I don’t quite understand the part of embedding visualizing. In your paper, what‘s does the item 5(4 3/5−3 4/10) mean?

**Comment by jilljenn** [comment]
Sorry for the delay. It's item 5 which corresponds to fraction (4 + 3/5) - (3 + 4/10).
See all items on (DeCarlo, 2011):

![Capture d’écran de 2022-04-19 01-21-58](https://user-images.githubusercontent.com/1729581/163892147-4b5edeb2-6f7e-4242-b5f8-2def49f07e1b.png)

> DeCarlo, L. T. (2011). On the analysis of fraction subtraction data: The DINA model, classification, latent class sizes, and the Q-matrix. Applied Psychological Measurement, 35(1), 8-26. https://journals.sagepub.com/doi/pdf/10.1177/0146621610377081
