### ISSUE TITLE
TypeError: load_folds() missing 2 required positional arguments: 'options' and 'df'

### ISSUE THREAD

**Issue by bernardoleite** [jilljenn/ktm#8]
Hi there! Thanks for your implementation.

After running the following commands:

```
python encode.py --dataset assistments09 --skills --wins --fails
python lr.py data/dummy/X-swf.npz
```

The following output error reveals:
```
TypeError: load_folds() missing 2 required positional arguments: 'options' and 'df'
```

Am I doing something wrong?
Thanks in advance.

**Comment by jilljenn** [comment]
Sorry just noticed!

**Comment by jilljenn** [comment]
Could you please check? It should be fixed now.
